import z from 'zod'
export const IngredientNutritionSchema = z.object({
  id: z.string().uuid(),
  ingredientId: z.string().uuid(),
  carbohydrates: z.number(),
  proteins: z.number(),
  fats: z.number(),
  saturatedFat: z.number(),
  unsaturatedFat: z.number(),
  transFat: z.number(),
  fiber: z.number(),
  sugars: z.number(),
  cholesterol: z.number(),
  sodium: z.number(),
  potassium: z.number(),
  calcium: z.number(),
  iron: z.number(),
  magnesium: z.number(),
  zinc: z.number(),
  vitaminA: z.number(),
  vitaminB1: z.number(),
  vitaminB2: z.number(),
  vitaminB3: z.number(),
  vitaminB5: z.number(),
  vitaminB6: z.number(),
  vitaminB7: z.number(),
  vitaminB9: z.number(),
  vitaminB12: z.number(),
  vitaminC: z.number(),
  vitaminD: z.number(),
  vitaminE: z.number(),
  vitaminK: z.number(),
})
