import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seed() {
  // Clear existing ingredients
  await prisma.ingredient.deleteMany()

  // Seed ingredients
  await prisma.ingredient.createMany({
    data: [
      {
        ingredientName: 'Rice',
        calories: 360,
        carbohydratesAmount: 79.34,
        fatsAmount: 0.58,
        proteinsAmount: 6.61,
        sugarAmount: 0.05,
        ironAmount: 1.5,
        sodiumAmount: 1,
        potassiumAmount: 29,
        vitaminC: 0,
        vitaminB6: 0.15,
        vitaminB12: 0
      },
      {
        ingredientName: 'Basmati rice',
        calories: 354,
        carbohydratesAmount: 71.07,
        fatsAmount: 2.857,
        proteinsAmount: 8.929,
        sugarAmount: 0.05,
        ironAmount: 1.5,
        sodiumAmount: 1,
        potassiumAmount: 29,
        vitaminC: 0,
        vitaminB6: 0.15,
        vitaminB12: 0
      },
      {
        ingredientName: 'Sushi rice',
        calories: 180,
        carbohydratesAmount: 28,
        fatsAmount: 0,
        proteinsAmount: 2,
        sugarAmount: 0.05,
        ironAmount: 1.5,
        sodiumAmount: 1,
        potassiumAmount: 29,
        vitaminC: 0,
        vitaminB6: 0.15,
        vitaminB12: 0
      },
      {
        ingredientName: 'Eggplant',
        calories: 25,
        carbohydratesAmount: 5.88,
        fatsAmount: 0.18,
        proteinsAmount: 0.98,
        sugarAmount: 2.9,
        ironAmount: 0.19,
        sodiumAmount: 2,
        potassiumAmount: 190,
        vitaminC: 2,
        vitaminB6: 0.15,
        vitaminB12: 0
      },
      {
        ingredientName: 'Okra',
        calories: 33,
        carbohydratesAmount: 7.45,
        fatsAmount: 0.19,
        proteinsAmount: 1.9,
        sugarAmount: 1.5,
        ironAmount: 0.8,
        sodiumAmount: 7,
        potassiumAmount: 299,
        vitaminC: 23,
        vitaminB6: 0.2,
        vitaminB12: 0
      },
      {
        ingredientName: 'Pastirma',
        calories: 164,
        carbohydratesAmount: 2,
        fatsAmount: 8,
        proteinsAmount: 21,
        sugarAmount: 0,
        ironAmount: 0.62,
        sodiumAmount: 248,
        potassiumAmount: 66,
        vitaminC: 0.4,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Peas',
        calories: 81,
        carbohydratesAmount: 14.5,
        fatsAmount: 0.41,
        proteinsAmount: 5.5,
        sugarAmount: 8.22,
        ironAmount: 2.13,
        sodiumAmount: 7.25,
        potassiumAmount: 353.8,
        vitaminC: 40,
        vitaminB6: 0.11,
        vitaminB12: 0
      },
      {
        ingredientName: 'Onion',
        calories: 40,
        carbohydratesAmount: 9.34,
        fatsAmount: 0.1,
        proteinsAmount: 1.1,
        sugarAmount: 4.71,
        ironAmount: 0.21,
        sodiumAmount: 3.3,
        potassiumAmount: 158.4,
        vitaminC: 4,
        vitaminB6: 0.12,
        vitaminB12: 0
      },
      {
        ingredientName: 'Duck',
        calories: 404,
        carbohydratesAmount: 0,
        fatsAmount: 39.34,
        proteinsAmount: 18.28,
        sugarAmount: 0,
        ironAmount: 2.7,
        sodiumAmount: 55,
        potassiumAmount: 240,
        vitaminC: 0,
        vitaminB6: 0.27,
        vitaminB12: 0.3
      },
      {
        ingredientName: 'Potatoes',
        calories: 87,
        carbohydratesAmount: 20.1,
        fatsAmount: 0.1,
        proteinsAmount: 1.9,
        sugarAmount: 2.13,
        ironAmount: 0.65,
        sodiumAmount: 4,
        potassiumAmount: 620,
        vitaminC: 17,
        vitaminB6: 0.3,
        vitaminB12: 0
      },
      {
        ingredientName: 'Breadcrumbs',
        calories: 395,
        carbohydratesAmount: 72,
        fatsAmount: 5.3,
        proteinsAmount: 13.35,
        sugarAmount: 5,
        ironAmount: 4,
        sodiumAmount: 400,
        potassiumAmount: 200,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'Spices',
        calories: 32,
        carbohydratesAmount: 6.33,
        fatsAmount: 0,
        proteinsAmount: 1.27,
        sugarAmount: 0,
        ironAmount: 17,
        sodiumAmount: 10,
        potassiumAmount: 700,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 0
      },
      {
        ingredientName: 'Eggs',
        calories: 143,
        carbohydratesAmount: 0.72,
        fatsAmount: 9.51,
        proteinsAmount: 12.56,
        sugarAmount: 0.37,
        ironAmount: 1.75,
        sodiumAmount: 124,
        potassiumAmount: 126,
        vitaminC: 0,
        vitaminB6: 0.12,
        vitaminB12: 1.11
      },
      {
        ingredientName: 'Baking powder',
        calories: 53,
        carbohydratesAmount: 27.7,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 28000,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Turkey',
        calories: 120,
        carbohydratesAmount: 0.24,
        fatsAmount: 2.86,
        proteinsAmount: 24,
        sugarAmount: 0,
        ironAmount: 4.1,
        sodiumAmount: 197,
        potassiumAmount: 830,
        vitaminC: 0,
        vitaminB6: 1.3,
        vitaminB12: 1.2
      },
      {
        ingredientName: 'Tuna',
        calories: 108,
        carbohydratesAmount: 0,
        fatsAmount: 0.95,
        proteinsAmount: 23.38,
        sugarAmount: 0,
        ironAmount: 0.77,
        sodiumAmount: 45,
        potassiumAmount: 441,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 2.1
      },
      {
        ingredientName: 'Garlic',
        calories: 149,
        carbohydratesAmount: 33.06,
        fatsAmount: 0.5,
        proteinsAmount: 6.36,
        sugarAmount: 1,
        ironAmount: 1.7,
        sodiumAmount: 17,
        potassiumAmount: 401,
        vitaminC: 31,
        vitaminB6: 0.188,
        vitaminB12: 0
      },
      {
        ingredientName: 'Parmesan cheese',
        calories: 420,
        carbohydratesAmount: 13.91,
        fatsAmount: 28,
        proteinsAmount: 28.42,
        sugarAmount: 0.9,
        ironAmount: 0.2,
        sodiumAmount: 1802,
        potassiumAmount: 180,
        vitaminC: 0,
        vitaminB6: 0.045,
        vitaminB12: 1.2
      },
      {
        ingredientName: 'White cheese',
        calories: 264,
        carbohydratesAmount: 4.09,
        fatsAmount: 21.28,
        proteinsAmount: 14.21,
        sugarAmount: 0.5,
        ironAmount: 0.1,
        sodiumAmount: 1710,
        potassiumAmount: 100,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0.75
      },
      {
        ingredientName: 'Roquefort cheese',
        calories: 369,
        carbohydratesAmount: 2,
        fatsAmount: 30.64,
        proteinsAmount: 21.54,
        sugarAmount: 0.7,
        ironAmount: 0.3,
        sodiumAmount: 1809,
        potassiumAmount: 100,
        vitaminC: 0,
        vitaminB6: 0.04,
        vitaminB12: 0.7
      },
      {
        ingredientName: 'Rumi cheese',
        calories: 0,
        carbohydratesAmount: 0,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0.6,
        ironAmount: 0.3,
        sodiumAmount: 1700,
        potassiumAmount: 90,
        vitaminC: 0,
        vitaminB6: 0.03,
        vitaminB12: 1.0
      },
      {
        ingredientName: 'Cheddar cheese',
        calories: 400,
        carbohydratesAmount: 1.3,
        fatsAmount: 33.1,
        proteinsAmount: 24.9,
        sugarAmount: 1,
        ironAmount: 0.2,
        sodiumAmount: 644,
        potassiumAmount: 76,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0.83
      },
      {
        ingredientName: 'Cottage cheese',
        calories: 98,
        carbohydratesAmount: 3.4,
        fatsAmount: 1,
        proteinsAmount: 11,
        sugarAmount: 0.5,
        ironAmount: 0.1,
        sodiumAmount: 500,
        potassiumAmount: 104,
        vitaminC: 0,
        vitaminB6: 0.04,
        vitaminB12: 0.75
      },
      {
        ingredientName: 'Mozzarella cheese',
        calories: 280,
        carbohydratesAmount: 2.2,
        fatsAmount: 17,
        proteinsAmount: 22.5,
        sugarAmount: 1.2,
        ironAmount: 0.25,
        sodiumAmount: 627,
        potassiumAmount: 95,
        vitaminC: 1.0,
        vitaminB6: 0.06,
        vitaminB12: 1.5
      },
      {
        ingredientName: 'Carrot',
        calories: 41,
        carbohydratesAmount: 9.58,
        fatsAmount: 0.24,
        proteinsAmount: 0.93,
        sugarAmount: 4.7,
        ironAmount: 0.3,
        sodiumAmount: 69,
        potassiumAmount: 320,
        vitaminC: 5.9,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'Goulash',
        calories: 299,
        carbohydratesAmount: 52.6,
        fatsAmount: 6,
        proteinsAmount: 7.1,
        sugarAmount: 0,
        ironAmount: 1.4,
        sodiumAmount: 137,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0.07,
        vitaminB12: 0
      },
      {
        ingredientName: 'Shrimp',
        calories: 80,
        carbohydratesAmount: 0,
        fatsAmount: 0.9,
        proteinsAmount: 20.4,
        sugarAmount: 0,
        ironAmount: 0.5,
        sodiumAmount: 119,
        potassiumAmount: 260,
        vitaminC: 0,
        vitaminB6: 0.24,
        vitaminB12: 1.7
      },
      {
        ingredientName: 'Coconut',
        calories: 354,
        carbohydratesAmount: 15.23,
        fatsAmount: 33.49,
        proteinsAmount: 3.33,
        sugarAmount: 6.2,
        ironAmount: 2.4,
        sodiumAmount: 20,
        potassiumAmount: 356,
        vitaminC: 3.3,
        vitaminB6: 0.3,
        vitaminB12: 0
      },
      {
        ingredientName: 'Jelly',
        calories: 60,
        carbohydratesAmount: 13,
        fatsAmount: 0,
        proteinsAmount: 1,
        sugarAmount: 86,
        ironAmount: 0.13,
        sodiumAmount: 466,
        potassiumAmount: 7,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Milk',
        calories: 61,
        carbohydratesAmount: 4.8,
        fatsAmount: 3.25,
        proteinsAmount: 3.15,
        sugarAmount: 4.6,
        ironAmount: 0.03,
        sodiumAmount: 44,
        potassiumAmount: 150,
        vitaminC: 0,
        vitaminB6: 0.04,
        vitaminB12: 0.45
      },
      {
        ingredientName: 'Pigeon',
        calories: 134,
        carbohydratesAmount: 0,
        fatsAmount: 5.4,
        proteinsAmount: 21.8,
        sugarAmount: 0,
        ironAmount: 2.1,
        sodiumAmount: 72,
        potassiumAmount: 280,
        vitaminC: 0,
        vitaminB6: 0.5,
        vitaminB12: 1.0
      },
      {
        ingredientName: 'Chickpeas',
        calories: 364,
        carbohydratesAmount: 60.65,
        fatsAmount: 6.04,
        proteinsAmount: 19.3,
        sugarAmount: 10.7,
        ironAmount: 6.24,
        sodiumAmount: 24,
        potassiumAmount: 875,
        vitaminC: 0,
        vitaminB6: 0.5,
        vitaminB12: 0
      },
      {
        ingredientName: 'Baladi bread',
        calories: 266,
        carbohydratesAmount: 51.2,
        fatsAmount: 1.4,
        proteinsAmount: 9.1,
        sugarAmount: 5,
        ironAmount: 3.6,
        sodiumAmount: 400,
        potassiumAmount: 115,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'White vinegar',
        calories: 18,
        carbohydratesAmount: 0.04,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 5,
        potassiumAmount: 1,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Rice vinegar',
        calories: 21,
        carbohydratesAmount: 5,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 5,
        ironAmount: 0,
        sodiumAmount: 5,
        potassiumAmount: 1,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Yeast',
        calories: 325,
        carbohydratesAmount: 34,
        fatsAmount: 6,
        proteinsAmount: 33,
        sugarAmount: 0,
        ironAmount: 5,
        sodiumAmount: 30,
        potassiumAmount: 500,
        vitaminC: 0,
        vitaminB6: 1.3,
        vitaminB12: 0
      },
      {
        ingredientName: 'Cucumber',
        calories: 15,
        carbohydratesAmount: 3.63,
        fatsAmount: 0.11,
        proteinsAmount: 0.65,
        sugarAmount: 1.7,
        ironAmount: 0.3,
        sodiumAmount: 2,
        potassiumAmount: 147,
        vitaminC: 2.8,
        vitaminB6: 0.04,
        vitaminB12: 0
      },
      {
        ingredientName: 'Chicken',
        calories: 165,
        carbohydratesAmount: 0,
        fatsAmount: 3.57,
        proteinsAmount: 31,
        sugarAmount: 0,
        ironAmount: 0.64,
        sodiumAmount: 70,
        potassiumAmount: 522,
        vitaminC: 0,
        vitaminB6: 0.51,
        vitaminB12: 0.56
      },
      {
        ingredientName: 'White flour',
        calories: 364,
        carbohydratesAmount: 76,
        fatsAmount: 1,
        proteinsAmount: 10,
        sugarAmount: 0,
        ironAmount: 1.2,
        sodiumAmount: 2,
        potassiumAmount: 107,
        vitaminC: 0,
        vitaminB6: 0.08,
        vitaminB12: 0
      },
      {
        ingredientName: 'Tortillas',
        calories: 299,
        carbohydratesAmount: 52.6,
        fatsAmount: 6,
        proteinsAmount: 7.1,
        sugarAmount: 1.0,
        ironAmount: 1.3,
        sodiumAmount: 200,
        potassiumAmount: 60,
        vitaminC: 0,
        vitaminB6: 0.05,
        vitaminB12: 0
      },
      {
        ingredientName: 'Butter',
        calories: 717,
        carbohydratesAmount: 0,
        fatsAmount: 81,
        proteinsAmount: 0.85,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 2,
        potassiumAmount: 1.2,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Raisins',
        calories: 299,
        carbohydratesAmount: 79,
        fatsAmount: 0.46,
        proteinsAmount: 3.1,
        sugarAmount: 59,
        ironAmount: 1.9,
        sodiumAmount: 11,
        potassiumAmount: 749,
        vitaminC: 0,
        vitaminB6: 0.15,
        vitaminB12: 0
      },
      {
        ingredientName: 'Oil',
        calories: 884,
        carbohydratesAmount: 0,
        fatsAmount: 100,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Olive oil',
        calories: 884,
        carbohydratesAmount: 0,
        fatsAmount: 100,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Green olives',
        calories: 145,
        carbohydratesAmount: 3.84,
        fatsAmount: 15.32,
        proteinsAmount: 1,
        sugarAmount: 3.3,
        ironAmount: 1.6,
        sodiumAmount: 1556,
        potassiumAmount: 8,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Spinach',
        calories: 23,
        carbohydratesAmount: 3.63,
        fatsAmount: 0.39,
        proteinsAmount: 2.86,
        sugarAmount: 0.43,
        ironAmount: 3.6,
        sodiumAmount: 79,
        potassiumAmount: 466,
        vitaminC: 9.8,
        vitaminB6: 0.24,
        vitaminB12: 0
      },
      {
        ingredientName: 'Sausage',
        calories: 304,
        carbohydratesAmount: 0,
        fatsAmount: 26.53,
        proteinsAmount: 15.09,
        sugarAmount: 0,
        ironAmount: 1.2,
        sodiumAmount: 731,
        potassiumAmount: 253,
        vitaminC: 2,
        vitaminB6: 0.3,
        vitaminB12: 0.9
      },
      {
        ingredientName: 'Sugar',
        calories: 387,
        carbohydratesAmount: 99.98,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 100,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Quail',
        calories: 192,
        carbohydratesAmount: 0,
        fatsAmount: 12.05,
        proteinsAmount: 19.63,
        sugarAmount: 0,
        ironAmount: 3.0,
        sodiumAmount: 60,
        potassiumAmount: 220,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 1.0
      },
      {
        ingredientName: 'Sesame',
        calories: 573,
        carbohydratesAmount: 23.45,
        fatsAmount: 49.67,
        proteinsAmount: 17.73,
        sugarAmount: 0.3,
        ironAmount: 14.6,
        sodiumAmount: 11,
        potassiumAmount: 468,
        vitaminC: 0,
        vitaminB6: 0.79,
        vitaminB12: 0
      },
      {
        ingredientName: 'Fish',
        calories: 84,
        carbohydratesAmount: 0,
        fatsAmount: 0.92,
        proteinsAmount: 17.76,
        sugarAmount: 0,
        ironAmount: 0.5,
        sodiumAmount: 60,
        potassiumAmount: 350,
        vitaminC: 0,
        vitaminB6: 0.2,
        vitaminB12: 1.0
      },
      {
        ingredientName: 'Margarine',
        calories: 876,
        carbohydratesAmount: 0,
        fatsAmount: 99,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Farina',
        calories: 360,
        carbohydratesAmount: 72.8,
        fatsAmount: 1.05,
        proteinsAmount: 12.7,
        sugarAmount: 0.3,
        ironAmount: 2,
        sodiumAmount: 2,
        potassiumAmount: 186,
        vitaminC: 0,
        vitaminB6: 0.02,
        vitaminB12: 0
      },
      {
        ingredientName: 'Chili',
        calories: 40,
        carbohydratesAmount: 9,
        fatsAmount: 0.4,
        proteinsAmount: 1.9,
        sugarAmount: 5,
        ironAmount: 3,
        sodiumAmount: 7,
        potassiumAmount: 340,
        vitaminC: 143,
        vitaminB6: 0.5,
        vitaminB12: 0
      },
      {
        ingredientName: 'Vermicelli',
        calories: 373,
        carbohydratesAmount: 78,
        fatsAmount: 0.6,
        proteinsAmount: 10,
        sugarAmount: 3,
        ironAmount: 1.1,
        sodiumAmount: 6,
        potassiumAmount: 24,
        vitaminC: 0,
        vitaminB6: 0.03,
        vitaminB12: 0
      },
      {
        ingredientName: 'Tahini',
        calories: 595,
        carbohydratesAmount: 21.4,
        fatsAmount: 53.7,
        proteinsAmount: 17.8,
        sugarAmount: 0.49,
        ironAmount: 9,
        sodiumAmount: 5,
        potassiumAmount: 414,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 0
      },
      {
        ingredientName: 'Tomatoes',
        calories: 18,
        carbohydratesAmount: 3.9,
        fatsAmount: 0.2,
        proteinsAmount: 0.9,
        sugarAmount: 3.9,
        ironAmount: 0.4,
        sodiumAmount: 9,
        potassiumAmount: 353,
        vitaminC: 23,
        vitaminB6: 0.08,
        vitaminB12: 0
      },
      {
        ingredientName: 'Yellow lentil',
        calories: 353,
        carbohydratesAmount: 60.08,
        fatsAmount: 1.06,
        proteinsAmount: 25.8,
        sugarAmount: 3.9,
        ironAmount: 14.5,
        sodiumAmount: 11.5,
        potassiumAmount: 1834,
        vitaminC: 0,
        vitaminB6: 0.49,
        vitaminB12: 0
      },
      {
        ingredientName: 'Black lentil',
        calories: 350,
        carbohydratesAmount: 70,
        fatsAmount: 4,
        proteinsAmount: 26,
        sugarAmount: 3.9,
        ironAmount: 14.5,
        sodiumAmount: 11.5,
        potassiumAmount: 1834,
        vitaminC: 0,
        vitaminB6: 0.49,
        vitaminB12: 0
      },
      {
        ingredientName: 'Honey',
        calories: 304,
        carbohydratesAmount: 82.4,
        fatsAmount: 0,
        proteinsAmount: 0.3,
        sugarAmount: 82,
        ironAmount: 0,
        sodiumAmount: 4,
        potassiumAmount: 52,
        vitaminC: 0,
        vitaminB6: 0.075,
        vitaminB12: 0
      },
      {
        ingredientName: 'Orange juice',
        calories: 45,
        carbohydratesAmount: 10.4,
        fatsAmount: 0.2,
        proteinsAmount: 0.7,
        sugarAmount: 8.4,
        ironAmount: 0.2,
        sodiumAmount: 1,
        potassiumAmount: 200,
        vitaminC: 50,
        vitaminB6: 0.08,
        vitaminB12: 0
      },
      {
        ingredientName: 'Lemon juice',
        calories: 25,
        carbohydratesAmount: 8.63,
        fatsAmount: 0,
        proteinsAmount: 0.38,
        sugarAmount: 2.5,
        ironAmount: 0.06,
        sodiumAmount: 1,
        potassiumAmount: 16,
        vitaminC: 38,
        vitaminB6: 0.04,
        vitaminB12: 0
      },
      {
        ingredientName: 'White beans',
        calories: 673,
        carbohydratesAmount: 71,
        fatsAmount: 2,
        proteinsAmount: 27,
        sugarAmount: 2,
        ironAmount: 5,
        sodiumAmount: 5,
        potassiumAmount: 1500,
        vitaminC: 0,
        vitaminB6: 0.38,
        vitaminB12: 0
      },
      {
        ingredientName: 'Vanilla',
        calories: 288,
        carbohydratesAmount: 12.65,
        fatsAmount: 0.06,
        proteinsAmount: 0.06,
        sugarAmount: 67,
        ironAmount: 0.01,
        sodiumAmount: 9,
        potassiumAmount: 148,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Freekeh',
        calories: 140,
        carbohydratesAmount: 30,
        fatsAmount: 1,
        proteinsAmount: 7,
        sugarAmount: 1,
        ironAmount: 2,
        sodiumAmount: 0,
        potassiumAmount: 352,
        vitaminC: 0,
        vitaminB6: 0.09,
        vitaminB12: 0
      },
      {
        ingredientName: 'Pepper',
        calories: 20,
        carbohydratesAmount: 4.5,
        fatsAmount: 0.2,
        proteinsAmount: 0.9,
        sugarAmount: 4,
        ironAmount: 1.3,
        sodiumAmount: 4,
        potassiumAmount: 211,
        vitaminC: 134,
        vitaminB6: 0.2,
        vitaminB12: 0
      },
      {
        ingredientName: 'Green pepper',
        calories: 40,
        carbohydratesAmount: 9,
        fatsAmount: 0.4,
        proteinsAmount: 1.9,
        sugarAmount: 4,
        ironAmount: 1.3,
        sodiumAmount: 4,
        potassiumAmount: 211,
        vitaminC: 134,
        vitaminB6: 0.2,
        vitaminB12: 0
      },
      {
        ingredientName: 'Black pepper',
        calories: 251,
        carbohydratesAmount: 64,
        fatsAmount: 3.3,
        proteinsAmount: 10,
        sugarAmount: 0.05,
        ironAmount: 0.88,
        sodiumAmount: 0.6,
        potassiumAmount: 11.5,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Peanuts',
        calories: 567,
        carbohydratesAmount: 16.13,
        fatsAmount: 49.24,
        proteinsAmount: 25.8,
        sugarAmount: 4.7,
        ironAmount: 4.58,
        sodiumAmount: 18,
        potassiumAmount: 705,
        vitaminC: 0,
        vitaminB6: 0.51,
        vitaminB12: 0
      },
      {
        ingredientName: 'Fava beans',
        calories: 340,
        carbohydratesAmount: 66,
        fatsAmount: 1,
        proteinsAmount: 29,
        sugarAmount: 2.3,
        ironAmount: 2,
        sodiumAmount: 9,
        potassiumAmount: 1062,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Ful medames',
        calories: 110,
        carbohydratesAmount: 22.2,
        fatsAmount: 0.92,
        proteinsAmount: 10,
        sugarAmount: 2,
        ironAmount: 2,
        sodiumAmount: 5,
        potassiumAmount: 350,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Cinnamon',
        calories: 247,
        carbohydratesAmount: 80,
        fatsAmount: 1.24,
        proteinsAmount: 4,
        sugarAmount: 0.05,
        ironAmount: 0.88,
        sodiumAmount: 0.6,
        potassiumAmount: 11.5,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Cream',
        calories: 340,
        carbohydratesAmount: 3,
        fatsAmount: 35,
        proteinsAmount: 2.5,
        sugarAmount: 3.4,
        ironAmount: 2,
        sodiumAmount: 35,
        potassiumAmount: 110,
        vitaminC: 1.9,
        vitaminB6: 0.03,
        vitaminB12: 0.4
      },
      {
        ingredientName: 'Crab',
        calories: 83,
        carbohydratesAmount: 0,
        fatsAmount: 1,
        proteinsAmount: 19,
        sugarAmount: 0,
        ironAmount: 0.5,
        sodiumAmount: 39,
        potassiumAmount: 259,
        vitaminC: 0,
        vitaminB6: 0.18,
        vitaminB12: 12
      },
      {
        ingredientName: 'Calamari',
        calories: 92,
        carbohydratesAmount: 3.2,
        fatsAmount: 1.4,
        proteinsAmount: 15.6,
        sugarAmount: 0,
        ironAmount: 0.8,
        sodiumAmount: 44,
        potassiumAmount: 272,
        vitaminC: 0,
        vitaminB6: 0.18,
        vitaminB12: 1.2
      },
      {
        ingredientName: 'Liver',
        calories: 135,
        carbohydratesAmount: 3.9,
        fatsAmount: 3.6,
        proteinsAmount: 20.4,
        sugarAmount: 1.8,
        ironAmount: 5.4,
        sodiumAmount: 59,
        potassiumAmount: 287,
        vitaminC: 0,
        vitaminB6: 0.18,
        vitaminB12: 0.4
      },
      {
        ingredientName: 'Cabbage',
        calories: 25,
        carbohydratesAmount: 5.8,
        fatsAmount: 0.1,
        proteinsAmount: 1.3,
        sugarAmount: 3.2,
        ironAmount: 0.47,
        sodiumAmount: 18,
        potassiumAmount: 170,
        vitaminC: 36.6,
        vitaminB6: 0.124,
        vitaminB12: 0
      },
      {
        ingredientName: 'Green cabbage',
        calories: 49,
        carbohydratesAmount: 8.8,
        fatsAmount: 0.9,
        proteinsAmount: 4.3,
        sugarAmount: 3.2,
        ironAmount: 0.47,
        sodiumAmount: 18,
        potassiumAmount: 170,
        vitaminC: 36.6,
        vitaminB6: 0.124,
        vitaminB12: 0
      },
      {
        ingredientName: 'Green coriander',
        calories: 23,
        carbohydratesAmount: 3.67,
        fatsAmount: 0.52,
        proteinsAmount: 2.13,
        sugarAmount: 0,
        ironAmount: 0.07,
        sodiumAmount: 15,
        potassiumAmount: 83,
        vitaminC: 1.1,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Kunafa',
        calories: 307,
        carbohydratesAmount: 73.7,
        fatsAmount: 0.3,
        proteinsAmount: 2.3,
        sugarAmount: 32,
        ironAmount: 0.5,
        sodiumAmount: 160,
        potassiumAmount: 109,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Zucchini',
        calories: 16,
        carbohydratesAmount: 3.35,
        fatsAmount: 0.18,
        proteinsAmount: 1.21,
        sugarAmount: 2.5,
        ironAmount: 0.37,
        sodiumAmount: 10,
        potassiumAmount: 324,
        vitaminC: 22,
        vitaminB6: 0.2,
        vitaminB12: 0
      },
      {
        ingredientName: 'Leb',
        calories: 584,
        carbohydratesAmount: 20,
        fatsAmount: 51,
        proteinsAmount: 21,
        sugarAmount: 4,
        ironAmount: 0.05,
        sodiumAmount: 70,
        potassiumAmount: 150,
        vitaminC: 0,
        vitaminB6: 0.04,
        vitaminB12: 0.75
      },
      {
        ingredientName: 'Milk (duplicate)',
        calories: 61,
        carbohydratesAmount: 4.7,
        fatsAmount: 3.3,
        proteinsAmount: 3.5,
        sugarAmount: 4.7,
        ironAmount: 0.07,
        sodiumAmount: 44,
        potassiumAmount: 157,
        vitaminC: 2,
        vitaminB6: 0.06,
        vitaminB12: 0.9
      },
      {
        ingredientName: 'Meat',
        calories: 250,
        carbohydratesAmount: 0,
        fatsAmount: 15,
        proteinsAmount: 26,
        sugarAmount: 0,
        ironAmount: 1.6,
        sodiumAmount: 66,
        potassiumAmount: 220,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 2.1
      },
      {
        ingredientName: 'Steak',
        calories: 250,
        carbohydratesAmount: 0,
        fatsAmount: 18,
        proteinsAmount: 23,
        sugarAmount: 0,
        ironAmount: 2.21,
        sodiumAmount: 61,
        potassiumAmount: 270,
        vitaminC: 0,
        vitaminB6: 0.07,
        vitaminB12: 2.1
      },
      {
        ingredientName: 'Ground Beef',
        calories: 254,
        carbohydratesAmount: 0,
        fatsAmount: 20,
        proteinsAmount: 17.17,
        sugarAmount: 0,
        ironAmount: 4.66,
        sodiumAmount: 66,
        potassiumAmount: 220,
        vitaminC: 0,
        vitaminB6: 0.3,
        vitaminB12: 2.1
      },
      {
        ingredientName: 'Orzo',
        calories: 360,
        carbohydratesAmount: 71,
        fatsAmount: 3.5,
        proteinsAmount: 11,
        sugarAmount: 0.6,
        ironAmount: 0.6,
        sodiumAmount: 5,
        potassiumAmount: 50,
        vitaminC: 0,
        vitaminB6: 0.05,
        vitaminB12: 0
      },
      {
        ingredientName: 'Turnip',
        calories: 28,
        carbohydratesAmount: 6.43,
        fatsAmount: 0.1,
        proteinsAmount: 0.9,
        sugarAmount: 3.8,
        ironAmount: 0.36,
        sodiumAmount: 191,
        potassiumAmount: 191,
        vitaminC: 21,
        vitaminB6: 0.05,
        vitaminB12: 0
      },
      {
        ingredientName: 'Black eyed pea',
        calories: 338,
        carbohydratesAmount: 62,
        fatsAmount: 1.5,
        proteinsAmount: 21,
        sugarAmount: 4.7,
        ironAmount: 5.02,
        sodiumAmount: 5,
        potassiumAmount: 1400,
        vitaminC: 0,
        vitaminB6: 0.36,
        vitaminB12: 0
      },
      {
        ingredientName: 'Almond',
        calories: 579,
        carbohydratesAmount: 21.6,
        fatsAmount: 49.9,
        proteinsAmount: 21.2,
        sugarAmount: 4.4,
        ironAmount: 3.7,
        sodiumAmount: 1,
        potassiumAmount: 705,
        vitaminC: 0,
        vitaminB6: 0.14,
        vitaminB12: 0
      },
      {
        ingredientName: 'Lemon',
        calories: 29,
        carbohydratesAmount: 9.32,
        fatsAmount: 0.3,
        proteinsAmount: 1.1,
        sugarAmount: 2.5,
        ironAmount: 0.06,
        sodiumAmount: 1,
        potassiumAmount: 16,
        vitaminC: 38,
        vitaminB6: 0.04,
        vitaminB12: 0
      },
      {
        ingredientName: 'Water',
        calories: 0,
        carbohydratesAmount: 0,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Mayonnaise',
        calories: 680,
        carbohydratesAmount: 0.6,
        fatsAmount: 75,
        proteinsAmount: 0.7,
        sugarAmount: 0.6,
        ironAmount: 0,
        sodiumAmount: 635,
        potassiumAmount: 10,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Chicken broth',
        calories: 5,
        carbohydratesAmount: 0.7,
        fatsAmount: 0.1,
        proteinsAmount: 0.3,
        sugarAmount: 0.2,
        ironAmount: 0,
        sodiumAmount: 343,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Mushroom',
        calories: 22,
        carbohydratesAmount: 3.26,
        fatsAmount: 0.34,
        proteinsAmount: 3.09,
        sugarAmount: 1.98,
        ironAmount: 0.5,
        sodiumAmount: 5,
        potassiumAmount: 318,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'Macaroni',
        calories: 371,
        carbohydratesAmount: 75,
        fatsAmount: 1.51,
        proteinsAmount: 13,
        sugarAmount: 1.4,
        ironAmount: 5,
        sodiumAmount: 5,
        potassiumAmount: 223,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'Nuts',
        calories: 607,
        carbohydratesAmount: 21,
        fatsAmount: 54,
        proteinsAmount: 20,
        sugarAmount: 4,
        ironAmount: 5,
        sodiumAmount: 610,
        potassiumAmount: 610,
        vitaminC: 0,
        vitaminB6: 0.5,
        vitaminB12: 0
      },
      {
        ingredientName: 'Salt',
        calories: 0,
        carbohydratesAmount: 0,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 38744,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Molokhia',
        calories: 32,
        carbohydratesAmount: 5.6,
        fatsAmount: 0.4,
        proteinsAmount: 3.7,
        sugarAmount: 0.2,
        ironAmount: 2.7,
        sodiumAmount: 563,
        potassiumAmount: 1200,
        vitaminC: 0,
        vitaminB6: 0.2,
        vitaminB12: 0
      },
      {
        ingredientName: 'Mombar',
        calories: 174,
        carbohydratesAmount: 0,
        fatsAmount: 9.6,
        proteinsAmount: 19,
        sugarAmount: 0,
        ironAmount: 2,
        sodiumAmount: 200,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      },
      {
        ingredientName: 'Starch',
        calories: 381,
        carbohydratesAmount: 91,
        fatsAmount: 0,
        proteinsAmount: 0,
        sugarAmount: 0,
        ironAmount: 0,
        sodiumAmount: 0,
        potassiumAmount: 0,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Nori',
        calories: 35,
        carbohydratesAmount: 5.1,
        fatsAmount: 0.3,
        proteinsAmount: 5.8,
        sugarAmount: 1.6,
        ironAmount: 3,
        sodiumAmount: 50,
        potassiumAmount: 1500,
        vitaminC: 0,
        vitaminB6: 0,
        vitaminB12: 0
      },
      {
        ingredientName: 'Grape leaves',
        calories: 101,
        carbohydratesAmount: 21,
        fatsAmount: 1.5,
        proteinsAmount: 5.6,
        sugarAmount: 0.8,
        ironAmount: 2.8,
        sodiumAmount: 440,
        potassiumAmount: 270,
        vitaminC: 0,
        vitaminB6: 0.1,
        vitaminB12: 0
      }
    ]
  })

  console.log('Seeding completed.')
}

seed()
  .catch((e) => {
    console.error('Seeding failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

